src/books/urls.py
from django.urls import path

from .views import (BookDeleteView, BookDetailView, BookTitleDetailView,
                    BookTitleListView)

app_name = "books"

urlpatterns = [
    path("", BookTitleListView.as_view(), name="main"),
    path("<str:letter>/", BookTitleListView.as_view(), name="main"),
    path("<str:letter>/<slug:slug>/", BookTitleDetailView.as_view(), name="detail"),
    path(
        "<str:letter>/<slug:slug>/<str:book_id>/",
        BookDetailView.as_view(),
        name="detail_book",
    ),
    path(
        "<str:letter>/<slug:slug>/<str:book_id>/delete",
        BookDeleteView.as_view(),
        name="delete_book",
    ),
]

src/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from .views import (DashBoardView, change_theme, chart_data, login_view,
                    logout_view, otp_view, AboutView)

urlpatterns = [
    path("", DashBoardView.as_view(), name="home"),
    path("chart-data/", chart_data, name="data"),
    path("admin/", admin.site.urls),
    path("switch", change_theme, name="change_theme"),
    path("books/", include("books.urls", namespace="books")),
    path("rentals/", include("rentals.urls", namespace="rentals")),
    path("__reload__/", include("django_browser_reload.urls")),
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("otp/", otp_view, name="otp"),
    path("about/", AboutView.as_view(), name="about"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Book Rental Administration"
admin.site.index_title = "Book Management System"

src/templates/layout/navbar.html
{% load static %}

<!-- navbar -->
<nav class="flex items-center h-16 bg-slate-200 w-full z-10 text-black border border-slate-400 
    shadow-md shadow-slate-500 dark:bg-slate-600 dark:text-white rounded-lg">
    <div class="flex justify-between items-center w-full px-12 py-3">
        {% if request.user.is_authenticated %}
        <div class="bg-slate-300 hover:bg-slate-400 dark:bg-slate-500 rounded-full ml-2">
            <svg width="60" height="60" data-jdenticon-value="{{ request.user.username }}"></svg>
        </div>
        <div>
            <a href="{{ home_url }}"><img src="{% static 'image/book_rent.png' %}" class="h-14 w-38" alt="logo"></a>
        </div>
        <div class="flex items-center">
            <div class="relative" id="dropdown-box">
                <button id="btn-dropdown" class="flex items-center justify-center w-auto bg-slate-200 text-sm hover:bg-slate-300 border 
                border-slate-400 dark:bg-slate-500 rounded-lg drop-shadow-lg p-3 transition duration-300">
                    <span class="mr-2">MENU</span><i class="fa-solid fa-caret-down text-center"></i>
                </button>
                <div id="dropdown" class="hidden absolute items-center text-center bg-slate-200 min-w-full
                text-sm dark:bg-slate-600 rounded-lg drop-shadow-lg">
                    <ul class="text-base text-black dark:text-white">
                        <li>
                            <div class="block px-4 py-2 hover:bg-slate-300 dark:hover:bg-slate-500
                            rounded-lg transition duration-300 border border-slate-400">{{ request.user.username }}</div>
                        </li>
                        <li>
                            <a href="{% url 'logout' %}" class="block px-4 py-2 hover:bg-slate-300 dark:hover:bg-slate-500
                            rounded-lg transition duration-300 border border-slate-400">logout</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="bg-slate-300 hover:bg-slate-400 dark:bg-slate-500 rounded-full ml-3">
                <svg width="60" height="60" data-jdenticon-value="{{ request.user.username }}"></svg>
            </div>
        </div>
        {% endif %}

    </div>
</nav>

src/templates/layout/sidebar.html
{% url 'home' as home_url %}
{% url 'books:main' as books_url %}
{% url 'rentals:main' as rentals_url %}
{% url 'about' as about_url %}

<!-- Sidebar -->
<aside class="hidden md:block dark:bg-slate-600 bg-slate-200 h-screen w-full shadow-lg shadow-slate-500 
    dark:text-white pt-0 text-base text-black rounded-lg border border-slate-400" >
    <ul class="">
        <!-- dashboard -->
        <li>
            <a href="{{ home_url }}" class="flex flex-col place-items-center py-10 hover:bg-slate-300 
                dark:hover:bg-slate-500 rounded-sm transition duration-300" id="home-link">
                <i class="fa-solid fa-chart-pie fa-xl"></i>
                <p class="mt-4 text-wrap">Dashboard</p>
            </a>
        </li>
        <!-- books -->
        <li>
            <a href="{{ books_url }}" class="flex flex-col place-items-center py-10 hover:bg-slate-300 
                dark:hover:bg-slate-500 rounded-sm transition duration-300" id="books-link">
                <i class="fa-solid fa-book fa-xl"></i>
                <p class="mt-4 text-wrap">Books</p>
            </a>
        </li>
        <!-- rentals -->
        <li>
            <a href="{{ rentals_url }}" class="flex flex-col place-items-center py-10 hover:bg-slate-300 
                dark:hover:bg-slate-500 rounded-sm transition duration-300" id="rentals-link">
                <i class="fa-solid fa-bookmark fa-xl"></i>
                <p class="mt-4 text-wrap">Rentals</p>
            </a>
        </li>
        <!-- about -->
        <li>
            <a href="{{ about_url }}" class="flex flex-col place-items-center py-10 hover:bg-slate-300 
                dark:hover:bg-slate-500 rounded-sm transition duration-300 border-t border-slate-400" id="about-link">
                <i class="fa-solid fa-circle-question fa-xl"></i>
                <p class="mt-4 text-wrap">About</p>
            </a>
        </li>
    </ul>
</aside>

<!-- Highlight the current section in the sidebar -->
<script>
    document.addEventListener('DOMContentLoaded', function() {
        const currentPath = window.location.pathname;
        const homeLink = document.getElementById('home-link');
        const booksLink = document.getElementById('books-link');
        const rentalsLink = document.getElementById('rentals-link');
        const aboutLink = document.getElementById('about-link');

        if (currentPath === '{{ home_url }}') {
            homeLink.classList.add('bg-slate-500/50');
        } else if (currentPath.startsWith('{{ books_url }}')) {
            booksLink.classList.add('bg-slate-500/50');
        } else if (currentPath === '{{ rentals_url }}') {
            rentalsLink.classList.add('bg-slate-500/50');
        } else if (currentPath === '{{ about_url }}') {
            aboutLink.classList.add('bg-slate-500/50');
        }
    });
</script>