src/books/urls.py
from django.urls import path

from .views import (BookDeleteView, BookDetailView, BookTitleDetailView,
                    BookTitleListView)

app_name = "books"

urlpatterns = [
    path("", BookTitleListView.as_view(), name="main"),
    path("<str:letter>/", BookTitleListView.as_view(), name="main"),
    path("<str:letter>/<slug:slug>/", BookTitleDetailView.as_view(), name="detail"),
    path(
        "<str:letter>/<slug:slug>/<str:book_id>/",
        BookDetailView.as_view(),
        name="detail_book",
    ),
    path(
        "<str:letter>/<slug:slug>/<str:book_id>/delete",
        BookDeleteView.as_view(),
        name="delete_book",
    ),
]

src/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from .views import (DashBoardView, change_theme, chart_data, login_view,
                    logout_view, otp_view, AboutView)

urlpatterns = [
    path("", DashBoardView.as_view(), name="home"),
    path("chart-data/", chart_data, name="data"),
    path("admin/", admin.site.urls),
    path("switch", change_theme, name="change_theme"),
    path("books/", include("books.urls", namespace="books")),
    path("rentals/", include("rentals.urls", namespace="rentals")),
    path("__reload__/", include("django_browser_reload.urls")),
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("otp/", otp_view, name="otp"),
    path("about/", AboutView.as_view(), name="about"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Book Rental Administration"
admin.site.index_title = "Book Management System"

src/rentals/urls.py
from django.urls import path

from .views import (BookRentalHistoryView, CreateNewRentalView,
                    SelectDownloadRentalsView, UpdateRentalStatusView,
                    search_book_view)

app_name = "rentals"
urlpatterns = [
    path("", search_book_view, name="main"),
    path("<str:book_id>/", BookRentalHistoryView.as_view(), name="detail"),
    path("<str:book_id>/<pk>/", UpdateRentalStatusView.as_view(), name="update"),
    path("<str:book_id>/new", CreateNewRentalView.as_view(), name="new"),
    path(
        "<str:book_id>/download", SelectDownloadRentalsView.as_view(), name="download"
    ),
]

src/books/models.py
import uuid
from io import BytesIO

import qrcode
from django.core.files import File
from django.db import models
from django.urls import reverse
from django.utils.text import slugify

from authors.models import Author
from publishers.models import Publisher
from rentals.choices import STATUS_CHOICES

from .utils import hash_book_info


class BookTitle(models.Model):
    title = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(blank=True)
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    @property
    def books(self):
        # This is a property method that allows access to related Book objects
        # through the book_set manager. It returns all Book instances that are
        # associated with this BookTitle instance.
        return self.book_set.all()

    def get_absolute_url(self):
        # Extract the first letter of the title and convert it to lowercase.
        letter = self.title[0].lower()
        context = {"letter": letter, "slug": self.slug}
        return reverse("books:detail", kwargs=context)

    def __str__(self):
        return f"Book: {self.title}"

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
            # The slugify function takes a string and returns a URL-safe
            # version of it. It replaces spaces with hyphens, removes any
            # non-alphanumeric characters, and lowercases the string.
        super().save(*args, **kwargs)


class Book(models.Model):
    id = models.CharField(
        primary_key=True,
        unique=True,
        max_length=36,
        default=uuid.uuid4,
        editable=False,
    )
    title = models.ForeignKey(BookTitle, on_delete=models.CASCADE)
    isbn = models.CharField(max_length=255, blank=True)
    qr_code = models.ImageField(upload_to="qr_codes/", blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        # Extract the first letter of the title and convert it to lowercase.
        letter = self.title.title[0].lower()
        context = {
            "letter": letter,
            "slug": self.title.slug,
            "book_id": self.id,
        }
        return reverse("books:detail_book", kwargs=context)

    def delete_object(self):
        letter = self.title.title[0].lower()
        context = {
            "letter": letter,
            "slug": self.title.slug,
            "book_id": self.id,
        }
        return reverse("books:delete_book", kwargs=context)

    def __str__(self):
        return str(self.title)

    # obj.status замість obj.status()
    @property
    def status(self):
        # зберігаємо перший об'єкт,
        rental = self.rental_set.first()
        if not rental:
            return False
        return dict(STATUS_CHOICES).get(rental.status, "Невідомий статус")

    @property
    def rental_id(self):
        if len(self.rental_set.all()) > 0:
            return self.rental_set.first().id
        return None

    @property
    def is_available(self):
        rentals = self.rental_set.all()
        if rentals:
            return rentals.first().status == "1"
        return True

    def save(self, *args, **kwargs):
        """Generates ISBN and QR code before saving the book."""
        if not self.isbn:
            # self.isbn = str(uuid.uuid4()).replace("-", "")[:24].lower()
            self.isbn = hash_book_info(self.title.title, self.title.publisher.name)

            # Generate QR code
            qr = qrcode.QRCode(
                version=1,
                error_correction=qrcode.constants.ERROR_CORRECT_L,
                box_size=10,
                border=4,
            )
            qr.add_data(self.isbn)
            qr.make(fit=True)

            qr_img = qr.make_image(fill_color="black", back_color="white")

            # Save the QR code to a file
            fname = f"qr_code-{self.isbn}.png"
            buffer = BytesIO()
            qr_img.save(buffer, format="PNG")  # Directly save the QR code image
            self.qr_code.save(fname, File(buffer), save=False)  # Save QR code file
            buffer.close()

            super().save(*args, **kwargs)

src/books/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import BookTitle


class BookTitleForm(forms.ModelForm):
    class Meta:
        model = BookTitle
        fields = [
            "publisher",
            "author",
            "title",
        ]

    def clean(self):
        title = self.cleaned_data.get("title")
        if len(title) < 5:
            msg = "Title must be at least 5 characters long."
            # self.add_error("title", msg)
            raise ValidationError(msg)

        book_title_exists = BookTitle.objects.filter(title__iexact=title).exists()
        if book_title_exists:
            raise ValidationError("This title already exists. Please enter a new one.")

        return self.cleaned_data

src/books/views.py
import string

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import QuerySet
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views.generic import DeleteView, DetailView, FormView, ListView

from .forms import BookTitleForm
from .models import Book, BookTitle


class BookTitleListView(LoginRequiredMixin, FormView, ListView):
    """
    A view that displays a list of BookTitle objects and allows the user to add a new
    BookTitle object to the list.

    The view uses the BookTitleForm to validate the user's input. If the input is
    valid, it saves the form data to create a new BookTitle object and adds an
    informational message to be displayed to the user indicating that a new
    BookTitle has been successfully created.

    If the input is invalid, it adds an error message for each error to the messages
    framework, prefixes the message with the field name if the error is a field-
    specific error, and calls the parent class's form_invalid method.

    The view also overrides the get_success_url method to return the current URL
    as the success URL.
    """

    queryset: QuerySet[BookTitle] = BookTitle.objects.all()
    template_name: str = "books/main.html"
    context_object_name: str = "object_list"
    form_class: type = BookTitleForm

    def get_success_url(self) -> str:
        return self.request.path

    def form_valid(self, form: BookTitleForm) -> HttpResponse:
        # Save the form data to create a new BookTitle instance
        book_title: BookTitle = form.save()
        # Add an informational message to be displayed to the user indicating
        # that a new BookTitle has been successfully created
        messages.add_message(self.request, messages.INFO, f"{book_title} created.")
        # Call the parent class's form_valid method to complete the process
        # and redirect the user to the success URL
        return super().form_valid(form)

    def form_invalid(self, form: BookTitleForm) -> HttpResponse:
        self.object_list = self.get_queryset()

        # Loop through the form errors. For each error:
        for field_name, field_errors in form.errors.items():
            # If the error is an "__all__" error (i.e. not a field-specific error),
            # loop through the error messages and add a message for each one.
            if field_name == "__all__":
                for error_message in field_errors:
                    messages.add_message(self.request, messages.ERROR, error_message)
            # If the error is a field-specific error, loop through the error messages
            # and add a message for each one, but prefix the message with the field
            # name.
            else:
                for error_message in field_errors:
                    messages.add_message(
                        self.request,
                        messages.ERROR,
                        f"{field_name.capitalize()}: {error_message}",
                    )
        # Call the parent's form_invalid method.
        return super().form_invalid(form)

    def get_queryset(self) -> QuerySet[BookTitle]:
        parameter = self.kwargs.get("letter", "a")
        # The parameter is a single letter, so we filter the BookTitle objects
        # by the first letter of their title.
        return BookTitle.objects.filter(title__startswith=parameter)

    def get_context_data(self, **kwargs) -> dict:
        # Call the parent class's get_context_data method to get the context data.
        # Then add two additional values to the context data: "letters" and
        # "selected_letter".
        #
        # The "letters" value is a list of all the lowercase letters of the
        # alphabet. This is used in the template to render a list of all the
        # letters of the alphabet, and the "selected_letter" value is used to
        # determine which letter to highlight in the list.
        #
        # The "selected_letter" value is the value of the "letter" parameter from
        # the URL pattern (or "a" if no "letter" parameter is provided).
        context = super().get_context_data(**kwargs)
        context["letters"] = list(string.ascii_lowercase)
        context["selected_letter"] = self.kwargs.get("letter", "a")
        # Finally, return the context data.
        return context


# class BookListView(ListView):
#     template_name = "books/detail.html"
#     context_object_name = "object_list"
#     paginate_by = 2

#     def get_queryset(self):
#         # Get the slug parameter from the URL pattern. The slug parameter is
#         # the slug of the BookTitle object whose books we want to display.
#         title_slug = self.kwargs.get("slug")
#         # Get the BookTitle object with the given slug. If no BookTitle object
#         # exists with the given slug, 404.
#         book_title = get_object_or_404(BookTitle, slug=title_slug)
#         # Return a QuerySet of all the Book objects whose title is the
#         # BookTitle object we just retrieved.
#         return Book.objects.filter(title=book_title)


class BookTitleDetailView(LoginRequiredMixin, DetailView):
    model = BookTitle
    template_name = "books/detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["previus_page"] = reverse("books:main")
        return context


# def book_title_detail_view(request: HttpRequest, slug: str, letter: str) -> HttpResponse:
#     obj: BookTitle = get_object_or_404(BookTitle, slug=slug)
#     return render(request, "books/detail.html", {"obj": obj})


class BookDetailView(LoginRequiredMixin, DetailView):
    model = Book
    template_name = "books/detail_book.html"

    def get_object(self):
        id = self.kwargs.get("book_id")
        obj = get_object_or_404(Book, id=id)
        return obj


class BookDeleteView(LoginRequiredMixin, DeleteView):
    model = Book
    template_name = "books/confirm_delete.html"
    pk_url_kwarg = "book_id"

    def get_object(self):
        id = self.kwargs.get("book_id")
        obj = get_object_or_404(Book, id=id)
        return obj

    def get_success_url(self):
        messages.add_message(
            self.request,
            messages.INFO,
            f"Book {self.object.isbn} deleted.",
        )
        letter = self.kwargs.get("letter")
        slug = self.kwargs.get("slug")
        return reverse("books:detail", kwargs={"letter": letter, "slug": slug})

src/books/templates/books/confirm_delete.html
{% extends 'base.html' %}

{% block title %}
    Confirm delete
{% endblock title %}

{% block content %}
    <div class="w-full border border-slate-400
        bg-slate-200 dark:bg-slate-600 dark:hover:bg-slate-700 shadow-lg p-5 rounded-lg 
        hover:bg-slate-100 ">
        <h1 class="text-center text-2xl font-semibold text-slate-700 dark:text-white">
            Do you want to delete "{{ object.isbn }}" ???
        </h1>
        <div class="mt-4 text-center">Deleting a book title is a permanent action.
            <form method="POST">
                {% csrf_token %}
                <button type="submit" class="mt-4 bg-red-600 hover:bg-red-500 text-white font-semibold py-2 px-4 
                border border-red-600 rounded">delete</button>
            </form>
        </div>
    </div>
    
{% endblock %}

src/books/templates/books/detail.html
{% extends 'base.html' %}
{% block title %}
  Home
{% endblock %}

{% block content %}

{% if messages %}
	{% for message in messages %}
		{% if message.level_tag == 'info' %}
			{% include 'components/alert.html' with is_info=True title='Success' body=message %}
		{% endif %}
	{% endfor %}
{% endif %}

{% include 'components/header.html' with title=object.title description="Book title details" is_go_back=True previous_page=previous_page %}

    <!-- Table -->
    <div class="overflow-x-auto">
    <table class="w-full text-sm text-left text-gray-600 dark:text-gray-400 bg-gray-200">
        <thead class=" text-sm text-gray-700 uppercase dark:bg-slate-700 dark:text-gray-200 
           hover:dark:bg-slate-600">
            <tr class="border border-gray-800">
                <th scope="col" class="py-3 px-6">
                    #
                </th>
                <th scope="col" class="py-3 px-6">
                    title
                </th>
                <th scope="col" class="py-3 px-6">
                    book id
                </th>
                <th scope="col" class="py-3 px-6">
                    isbn
                </th>
                <th scope="col" class="py-3 px-6">
                    qr code
                </th>
                <th scope="col" class="py-3 px-6">
                    status
                </th>
                <th scope="col" class="py-3 px-6">
                    available
                </th>
                <th scope="col" class="py-3 px-6">
                    select
                </th>
                <th scope="col" class="py-3 px-6">
                    delete
                </th>
            </tr>
        </thead>
        <tbody>
            {% for obj in object.books %}
            <tr class="border-b hover:dark:bg-slate-600 dark:bg-slate-700 
              dark:border-gray-800 {% if not obj.is_read  %}font-bold{% endif %}">
                <td scope="row" class="py-4 px-6 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                    {{ forloop.counter }}
                </td>
                <td class="py-4 px-6">
                    {{ obj.title.title }}
                </td>
                <td class="py-4 px-6">
                    {{ obj.id }}
                </td>
                <td class="py-4 px-6">
                    {{ obj.isbn }}
                </td>
                <td class="py-4 px-6">
                    <img src="{{ obj.qr_code.url }}" alt="{{ obj.isbn }}" class="w-10 h-10 rounded-lg">
                </td>
                <td class="py-4 px-6">
                    {% if obj.status %} {{ obj.status}} {% else %} Not rented {% endif %}
                </td>
                <td class="py-4 px-6">
                    {% if obj.is_available %}
                      <span class="bg-green-200 text-green-800 text-xs font-medium mr-2 px-2.5 py-0.5 
                      rounded dark:bg-green-900/70 dark:text-green-300">Available</span>
                    {% else %}
                      <span class="bg-red-100 text-red-800 text-xs font-medium mr-2 px-2.5 py-0.5 
                      rounded dark:bg-red-900/70 dark:text-red-300">Not available</span>
                    {% endif %}
                </td>
                <td class="py-4 px-6 ">
                    {% include 'components/buttons/select_button.html' with href=obj.get_absolute_url %}
                </td>
                <td class="py-4 px-6">
                    {% include 'components/buttons/delete_button.html' with href=obj.delete_object %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    </div>



  {% comment %} {% for book in object.books %}
    <h1>{{ book.title.title }}</h1>
    <p>ISBN - {{ book.isbn }}</p>       
  {% empty %}
    <p>No books found.</p>
  {% endfor %} {% endcomment %}



<!-- Pagination -->
{% if is_paginated %}
    {# This will only be rendered if the page object has enough items to paginate. #}
    <div class="mt-3">
        {# An unordered list for the pagination links. #}
        <ul class="inline-flex items-center -space-x-px">
            {# If there is a previous page, show the left arrow. #}
            {% if page_obj.has_previous %}
                <li>
                    {# If there is a previous page, link to the previous page. #}
                    <a {% if page_obj.has_previous %}href="?page={{ page_obj.previous_page_number }}"
                        {% else %} href="" 
                        {% endif %} class="block px-3 py-2 leading-tight text-gray-500 bg-white border border-gray-300 rounded-l-lg 
                        hover:bg-gray-200 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 
                        dark:hover:bg-gray-700 dark:hover:text-white">                    
                        {# A left arrow icon. #}
                        <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                          <path fill-rule="evenodd" 
                          d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z" 
                          clip-rule="evenodd">
                          </path>
                        </svg>
                    </a>
                </li>
            {% endif %}

            {# Loop over all the page numbers. #}
            {% for i in page_obj.paginator.page_range %}
                {# If the current page number is the same as the loop index, show a bold link. #}
                {% if page_obj.number == i %}
                    <li>
                      <a class="px-3 py-2 leading-tight text-gray-600 dark:text-gray-100 bg-gray-200 
                        dark:bg-gray-700 border border-gray-300 hover:bg-white hover:text-gray-700  
                        dark:border-gray-700 dark:hover:bg-gray-700 dark:hover:text-white" 
                      href="?page={{ i }}">{{ i }}
                      </a>
                    </li>
                {# If the current page number is not the same as the loop index, show a regular link. #}
                {% else %}
                    <li>
                      <a class="px-3 py-2 leading-tight text-gray-500 bg-white border border-gray-300 
                        hover:bg-gray-100 hover:text-gray-700 
                        dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 
                        dark:hover:bg-gray-700 dark:hover:text-white" 
                      href="?page={{ i }}">{{ i }}
                      </a>
                    </li>
                {% endif %}
            {% endfor %}
 
            {# If there is a next page, show the right arrow. #}
            {% if page_obj.has_next %}
                <li>
                  {# If there is a next page, link to the next page. #}
                  <a {% if page_obj.has_next %}
                      href="?page={{ page_obj.next_page_number }}"
                    {% else %} 
                      href="" 
                    {% endif %} 
                      class="block px-3 py-2 leading-tight text-gray-500 bg-white border border-gray-300 rounded-r-lg 
                      hover:bg-gray-200 hover:text-gray-700 
                      dark:bg-gray-700 dark:border-gray-100 dark:text-gray-400 
                      dark:hover:bg-gray-600 dark:hover:text-white">                    
                      {# A right arrow icon. #}
                      <svg aria-hidden="true" 
                        class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" 
                        xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" 
                        clip-rule="evenodd">
                        </path>
                      </svg>
                    </a>
                  </li>
            {% endif %}
        </ul>
    </div>
{% endif %} 

{% endblock %}

src/books/templates/books/detail_book.html
{% extends 'base.html' %}
{% load static %}
 
{% block scripts %}
    <script src="{% static 'books/detail_book.js' %}" defer></script>
{% endblock scripts %}

{%block title %}
    Book detail
{% endblock title %}
 
 
{% block content %}
<!-- header -->
{% include "components/header.html" with title=object.title.title description=object.title.publisher.name is_go_back=True %}
 
<div class="flex justify-center p-2">
    <div class="flex flex-col items-center ">
        <div class="text-center mb-5 text-lg font-semibold">
            <!-- display status -->
            {% if object.is_available %}

                <a href="{% url 'rentals:new' object.id %}" class="bg-sky-600/70 hover:bg-sky-500/70 
                dark:hover:bg-sky-500/70 inline-flex items-center rounded-lg p-2 duration-300 
                text-white">Rent</a>

                {% if object.status %}
                    {{ object.status }}
                {% else %}
                    Not rented
                {% endif %}
                
            {% else %}
                Not available
            {% endif %}
                
        </div>
        <!-- add qr code -->
        <img src="{{ object.qr_code.url }}" alt="{{ object.isbn }} QR code" class="w-40 h-40 rounded-lg">
        <div class="mt-5 text-center">
            <!-- rent or change status buttons -->
            {% if not object.is_available %}
                <a href="{% url 'rentals:update' object.id object.rental_id %}" class="bg-sky-600/70 hover:bg-sky-500/70 dark:hover:bg-sky-700/70 
                inline-flex items-center rounded-lg p-3 duration-200 text-white">Change status</a>
                <a href="{% url 'rentals:detail' object.id %}" class="bg-rose-600/70 hover:bg-rose-500/70 dark:hover:bg-rose-700/70 
                inline-flex items-center rounded-lg p-3 duration-200 text-white ">History</a>
            {% endif %}
        </div>
    </div>  
</div>
 
<div class="flex justify-center">
    <div class="mt-6 p-1 rounded-lg relative bg-slate-300 dark:bg-slate-600 border 
        border-slate-500 dark:border-slate-900 text-slate-700 
        dark:text-slate-200 drop-shadow-md w-1/2">
        <!--code for copying to clipboard-->
        <div id="book-id-box" class="text-center">{{ object.id }}</div>
        <div class="absolute top-1 right-2 cursor-pointer dark:text-white" id="copy-btn-box">
            <i class="fa-solid fa-copy"></i>
        </div>
    </div>
</div>
 
 
{% endblock %}

src/books/templates/books/main.html
{% extends 'base.html' %} {% load widget_tweaks %} {% load static %}

{% block styles %}
  <link rel="stylesheet" href="{% static 'books/main.css' %}" />
{% endblock %}
{% block scripts %}
  <script src="{% static 'books/main.js' %}" defer></script>
  <script src="{% static 'js/form_modal.js' %}" defer></script>
{% endblock %}

{% block title %}
  BOOK LIST
{% endblock %}

<!-- content -->
{% block content %}
  {# Show any messages that are present #}
  {% if messages %}
    {% for message in messages %}
      {% if message.level_tag == 'info' %}
        {% include 'components/alert.html' with is_info=True title='Success' body=message %}
      {% elif message.level_tag == 'error' %}
        {% include 'components/alert.html' with is_info=False title='Error' body=message %}
      {% endif %}
    {% endfor %}
  {% endif %}

  <!-- form modal -->
  <div class="hidden relative z-50" aria-labelledby="modal-title" role="dialog" aria-modal="true" id="form-modal">
    <div class="fixed inset-0 bg-gray-500 bg-opacity-75"></div>
    <div class="fixed inset-0 z-10 overflow-y-auto">
      <div class="flex min-h-full items-center justify-center p-4 text-center" id="backdrop">
        <div class="relative transform overflow-hidden rounded-lg text-left shadow-xl transition-all my-8">
          <form action="" method="POST">
            {% csrf_token %}
            <div class="bg-white dark:text-white dark:bg-slate-300 pt-5 pb-4 px-8">
              <div class="mt-3 text-left">
                <h3 class="text-2xl font-medium leading-6 text-gray-900" id="modal-title">New book title</h3>
                <div class="mt-3">
                  <!-- Search form -->
                  <div class="mb-2">
                    <!-- Field for searching for a book title -->
                    <label for="{{ form.title.id_for_label }}" class="block font-semibold">title:</label>
                    {{ form.title|add_class:'bg-slate-100 text-black rounded-lg p-2 shadow-lg' }}
                  </div>
                  <div class="mb-2">
                    <!-- Field for searching for the author of a book title -->
                    <label for="{{ form.author.id_for_label }}" class="block font-semibold">author:</label>
                    {{ form.author|add_class:'bg-slate-100 text-black rounded-lg p-2 shadow-lg' }}
                  </div>
                  <div class="mb-2">
                    <!-- Field for searching for the publisher of a book title -->
                    <label for="{{ form.publisher.id_for_label }}" class="block font-semibold">publisher:</label>
                    {{ form.publisher|add_class:'bg-slate-100 text-black rounded-lg p-2 shadow-lg' }}
                  </div>
                </div>
              </div>
            </div>
            <div class="bg-gray-50 dark:text-white dark:bg-slate-400 px-4 py-3 sm:flex sm:flex-row-reverse sm:px-6">
              <button type="submit" class="bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded">save</button>
              <button type="button" id="cancel-btn" class="bg-red-500 hover:bg-red-600 text-white font-semibold py-2 px-4 border border-red-600 rounded mr-3">cancel</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>

<!-- header -->
{% include 'components/header.html' with title='Book Titles' description='List of all book titles' is_form_available=True icon="<i class='fa-solid fa-plus'></i>" %}

<!-- Letters -->
<div class="flex flex-wrap justify-center gap-2 items-center text-2xl py-2 font-medium font-serif
    border-b border-slate-400 text-slate-700 dark:text-white">
    {% for letter in letters %}
        <a href="{% url 'books:main' letter=letter %}" class="{% if letter == selected_letter %} 
        font-semibold underline text-2xl {% endif %} p-1">{{ letter }}</a>
    {% endfor %}
</div>

  <!-- List of book titles startswith the selected letter -->
{% if object_list %}
    <ul class="flex flex-col gap-5 py-10">
        {% for book_title in object_list %}
            <li>
                <a href="{{ book_title.get_absolute_url }}" class="flex flex-col items-center text-lg 
                border py-5 text-black bg-slate-200 hover:bg-slate-300 transition duration-300 shadow-md
                shadow-slate-500 rounded-lg dark:bg-slate-600 dark:hover:bg-slate-500 dark:border border-slate-400 
                dark:text-white">
                <p class="text-wrap">{{ book_title.title }}</p>
                </a>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p class="text-center text-2xl font-semibold py-10">No book titles found.</p>
{% endif %}
{% endblock %}